-- MySQL Script generated by MySQL Workbench
-- Mo 13 Apr 2015 14:15:32 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema beatshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beatshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beatshare` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `beatshare` ;

-- -----------------------------------------------------
-- Table `beatshare`.`tbl_music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beatshare`.`tbl_music` (
  `m_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `artist` VARCHAR(255) NULL,
  `genre` VARCHAR(255) NULL,
  PRIMARY KEY (`m_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `beatshare`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beatshare`.`tbl_user` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `token` VARCHAR(255) NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beatshare`.`tbl_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beatshare`.`tbl_list` (
  `l_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `rating` INT NULL,
  `u_id` INT NULL,
  PRIMARY KEY (`l_id`),
  INDEX `u_id_idx` (`u_id` ASC),
  CONSTRAINT `u_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `beatshare`.`tbl_user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beatshare`.`tbl_list_music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beatshare`.`tbl_list_music` (
  `m_id` INT NULL,
  `l_id` INT NULL,
  INDEX `l_id_idx` (`l_id` ASC),
  INDEX `m_id_idx` (`m_id` ASC),
  CONSTRAINT `l_id`
    FOREIGN KEY (`l_id`)
    REFERENCES `beatshare`.`tbl_list` (`l_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `m_id`
    FOREIGN KEY (`m_id`)
    REFERENCES `beatshare`.`tbl_music` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
